### ISSUE TITLE
Checklist before launching

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/rolling-blackout-belgium#14]
- [x] Where do we link to? → Twitter
- [x] How are other browsers doing?
- [x] Add Google Analytics
- [x] Add README
- [x] Add data attribution (maybe just in README)
- [x] Add repo description and link
